FROM universalrobots/ursim_e-series

# Install the URCap
#COPY externalcontrol-1.0.5.urcap /urcaps/externalcontrol-1.0.5.jar


# Tell docker we want to use bash instead of sh in general
SHELL ["/bin/bash", "-c"]
CMD [ "bash" ]

