- frame: base_link
  type: H # V: vertical, H: horizontal
  positions:
    start: [-0.7, 0.47, 1.33] # [m] x,y,z
    stop: [-0.4, 0.47, 1.33] # [m] x,y,z
# - frame: base_link
#   type: H # V: vertical, H: horizontal
#   positions:
#     start: [0.4, -0.2, 0.5] # [m] x,y,z
#     stop: [0.4, 0.2, 0.5] # [m] x,y,z
