- frame: base_link
  type: V # V: vertical, H: horizontal
  positions:
    start: [0.3, -0.15, 0.7] # [m] x,y,z
    stop: [0.3, 0.2, 0.289] # [m] x,y,z
- frame: base_link
  type: V # V: vertical, H: horizontal
  positions:
    start: [0.3, 0.5, 0.7] # [m] x,y,z
    stop: [0.3, 0.5, 0.289] # [m] x,y,z
