# docker-compose-common.yml
#
# This file is used to define the common settings for all the containers.
# It as to be extend for each new service needing it.
#
# @Author [Louis Munier] - lmunier@protonmail.com
# @version 0.4
# @Date 2024-11-07
#
# Copyright (c) 2024 - EPFL - LASA. All rights reserved.

services:
  common:
    build:
      context: ../..
      network: host
      dockerfile: docker/main_pkg/Dockerfile

    image: registry.gitlab.com/certh-iti-robotics-lab/robetarme/robetarme/ros-noetic/t5.3-irr-control:development
    container_name: ros_noetic_t5.3_irr_control_development

    stdin_open: true
    tty: true
    network_mode: host
    ipc: host

    environment:
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}

      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}

      # Build the code in debug mode to add extra safety due to the development stage
      - CMAKE_BUILD_TYPE=Debug # Release : only for production

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../../catkin_ws/src:/home/${USER}/catkin_ws/src
