services:
  # ROS without GPU support from NVIDIA
  ros:
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      - LIBVA_DRIVER_NAME=i965
    devices:
      - /dev/dri:/dev/dri
