#!/bin/bash
# Pre-commit to avoid :
# - pushing files larger than 5MB to the github repository
# - pushing changes to .gitmodules related to submodule docker_ros_coppeliasim

# Author: Louis Munier - lmunier@protonmail.com
# Date: 2024-10-11

# Maximum file size in bytes (10MB)
max_size=10000000

# Find files larger than the specified size
large_files=$(git diff --cached --name-only | xargs -I{} find {} -type f -size +${max_size}c 2>/dev/null)

if [ -n "$large_files" ]; then
  echo "The following files are too large to commit:"
  echo "$large_files"
  exit 1
fi

# Define a list of submodules to avoid pushing
submodules=("catkin_ws/src/wp5-extern")

if git diff --cached --name-only | grep -q '.gitmodules'; then
  for submodule in "${submodules[@]}"; do
    if git diff --cached .gitmodules | grep -q "$submodule"; then
      # Stash changes to .gitmodules related to the submodule
      git stash push -m "Stash .gitmodules changes for $submodule" .gitmodules
      echo "Stashed changes to .gitmodules related to $submodule"
    fi
  done
fi

exit 0
